version: '3.8'

services:
  lightfm-trainer:
    build:
      context: ..
      dockerfile: workflow/Dockerfile
    volumes:
      - ../app/artifacts:/app/artifacts
    environment:
      - PYTHONUNBUFFERED=1
    mem_limit: 12G
    memswap_limit: 14G
